// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIKpsYRFstHBbMsxMHKZD7y5ISUx7Iw1k',
    appId: '1:391139111749:web:57b7196e6879b4ea7dc42c',
    messagingSenderId: '391139111749',
    projectId: 'chatapp-d4e37',
    authDomain: 'chatapp-d4e37.firebaseapp.com',
    storageBucket: 'chatapp-d4e37.firebasestorage.app',
    measurementId: 'G-QMSS8SLJ0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZi6kRZCTxsgK_sV4Q8wDVGo-wYUBTdEU',
    appId: '1:391139111749:android:1fe2dd3954493d5d7dc42c',
    messagingSenderId: '391139111749',
    projectId: 'chatapp-d4e37',
    storageBucket: 'chatapp-d4e37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwwIeOJxZFYXxTUSR0vUa-KC1BeYca9tg',
    appId: '1:391139111749:ios:251dd01a7a5bdfa77dc42c',
    messagingSenderId: '391139111749',
    projectId: 'chatapp-d4e37',
    storageBucket: 'chatapp-d4e37.firebasestorage.app',
    iosBundleId: 'com.example.chatApplecation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwwIeOJxZFYXxTUSR0vUa-KC1BeYca9tg',
    appId: '1:391139111749:ios:251dd01a7a5bdfa77dc42c',
    messagingSenderId: '391139111749',
    projectId: 'chatapp-d4e37',
    storageBucket: 'chatapp-d4e37.firebasestorage.app',
    iosBundleId: 'com.example.chatApplecation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIKpsYRFstHBbMsxMHKZD7y5ISUx7Iw1k',
    appId: '1:391139111749:web:4fbbd6c6412a15fd7dc42c',
    messagingSenderId: '391139111749',
    projectId: 'chatapp-d4e37',
    authDomain: 'chatapp-d4e37.firebaseapp.com',
    storageBucket: 'chatapp-d4e37.firebasestorage.app',
    measurementId: 'G-B72TBYLDKG',
  );
}
